language: java
jdk:
 - oraclejdk8
script: >
  ./ngrok start sunrise -config=ngrok.yaml
  ./gradlew -Dspring.profiles.active=ci test
notifications:
  email:
    on_success: change
    on_failure: change
