language: java
jdk:
 - oraclejdk8
before_script: ./ngrok start sunrise -config=ngrok.yaml
script: ./gradlew -Dspring.profiles.active=ci test
notifications:
  email:
    on_success: change
    on_failure: change
